### ISSUE TITLE
GET requests should not be expected to have bodies

### ISSUE THREAD

**Issue by meteabduraman** [CakeVision/proiect_tehnologii_web#20]
Took a look here and realized you have this `/tasks/one` endpoint which is a GET but it expects a body which would actually contain the id of the task. Generally if we make a GET it's not intuitive to pass a body to it although it might work 🧐 would you think it would be better to have a **path param** here with the ID of the task itself?

from:
`GET /tasks/one, body: { id: 'some-id' }`
to:
`GET /tasks/some-id`

some docs on Express path params/route params: https://expressjs.com/en/guide/routing.html (<kbd>ctrl</kbd> + <kbd>f</kbd> for `Route parameters`)

_Originally posted by @meteabduraman in https://github.com/CakeVision/proiect_tehnologii_web/pull/19#discussion_r1869074216_

**Comment by CakeVision** [comment]
Thank you for the help!
