### ISSUE TITLE
Build OpenAPI Specification Swagger file(s)

### ISSUE THREAD

**Issue by meteabduraman** [CakeVision/proiect_tehnologii_web#9]
Have a **Swagger file** for the API/one for each of the APIs. A Swagger file helps clients that want to use your API to know how to communicate with it and what to expect as responses (it discloses information about the available endpoints, request bodies, response status codes, etc.)

❗️This is needed for the **2nd phase of the Project**, due **December 5th, 2024**❗️
❗️Checkout more details about the assignment on [online.ase.ro](https://online.ase.ro)❗️

Checkout [this example](https://editor-next.swagger.io/).

Additional links:
- [OpenAPI standard definition](https://swagger.io/specification/)
- [express-openapi](https://www.npmjs.com/package/express-openapi) npm library for automatic creation of Swagger files
- [Swagger Online Editor](https://editor-next.swagger.io/) helping to manually build the Swagger file

This file (or .zip archive of files) then should be uploaded on [online.ase.ro](https://online.ase.ro).

**Comment by meteabduraman** [comment]
@CakeVision can you link your Github project to the repository? Seems like I can't mark this issue as part of your Github project 🤔

**Comment by CakeVision** [comment]
will take care of it in a sec

**Comment by CakeVision** [comment]
the project seems to be linked properly![20241121_174635.jpg](https://github.com/user-attachments/assets/52405bb6-b361-460f-9a94-df480da33bdb)

we have tasks linked to the repo atm, Ill check permissions on the project

**Comment by CakeVision** [comment]
it was a permissions issue, had perms on the repo but not on the project.should work now.(mention that it was an issue only for @me, others had access to make issues).
PS: Scuzați engleza, am citit engleza si am ramas pe engleză

**Comment by meteabduraman** [comment]
@CakeVision thanks! I added this to your board, it’s a placeholder for the second phase of the webtech Project due December 5th 🫡

**Comment by CakeVision** [comment]
@meteabduraman Just want some clarification on the task, all backend endpoints need to be defined in the/a swagger file aka we have to make docs for the backend, right?

**Comment by meteabduraman** [comment]
@CakeVision correct, all endpoints of your API need to be part of the Swagger; if you have multiple APIs, you’ll need to create a Swagger for each one of the APIs
